CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level" varchar(20) NOT NULL,
  "teacher" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(100) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "students_courses" (
  "student_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "students_courses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "students_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");



INSERT INTO users (name, email, password, age, rol_id) VALUES ('cristian', 'cristian@gmail.com', '12345', 29, 3), ('alejandra', 'alejandra@gmail.com', '313342', 27, 2);

INSERT INTO categories (name) VALUES ('educacion'), ('deporte');

INSERT INTO users (name, email, password, age, rol_id) VALUES ('katherine', 'kathe@gmail.com', '98765', 22, 1), ('carlos', 'carlos@hotmail.com', '78463', 25, 1);

INSERT INTO courses (title, description, level, teacher, category_id) VALUES ('javascript', 'curso basico', 'principiantes', 3, 1);

INSERT INTO courses (title, description, level, teacher, category_id) VALUES ('futbol', 'teoria del futbol', 'principiantes', 2, 2);

INSERT INTO course_video (title, url, course_id) VALUES ('primer programa', 'https://www.youtube.com/watch?v=ZH4aLctVSEQ', 1), ('alineacion','https://www.youtube.com/watch?v=xEDNEQBIj-w', 2);

INSERT INTO students_courses (student_id, course_id) VALUES (1, 1), (2, 1), (3, 2);




